### PR TITLE
Fix nlpmodif compat

### PR DESCRIPTION
**Pull request by tmigot**

### CODE REVIEW

**Comment by tmigot** [comment]
@geoffroyleconte The update of what you sent me. Could you verify that it works with https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/pull/66 ?

**Comment by tmigot** [comment]
Besides, another thing would be to add `consistent_nlps(nlps, linear_api = true)` instead of just `consistent_nlps(nlps)`

**Comment by geoffroyleconte** [comment]
Why the changes on the test problems? I think that QuadraticModels was supposed to work on them before. Also I don't think that the function `get_slack_ind` is ever called in QuadraticModels since it uses its own `SlackModel` (which returns a QuadraticModel). But I'm not 100% sure because I do not really know what is doing NLPModelsTests, maybe it is using other AbstractNLPModels that are not QuadraticModels?

**Comment by tmigot** [comment]
I modified the problem using ADNLPModel, because there is now a specific constructor for the linear constraints.

NLPModelsTest test the consistency of the current model, but it also test the consistency of the slack-version of the model, cf https://github.com/JuliaSmoothOptimizers/NLPModelsTest.jl/blob/c535a4ce22774dc9bc7fb9e720a30a68fa515888/src/nlp/consistency.jl#L15. There was a bug of the slack version of the ADNLPModel

**Comment by geoffroyleconte** [comment]
OK thanks! So the QuadraticModels.jl tests call `SlackModel` on a model that is not a `QuadraticModel` at some point if I understood correctly? I still get the same error message.

**Comment by tmigot** [comment]
Yes, the last issues are not coming from the QuadraticModels but from the ADModels you are comparing to.

Weird, it does pass on my computer with the following config:
```
     Project QuadraticModels v0.8.1
      Status `C:\Users\tangi\Documents\cvs\QuadraticModels.jl\Project.toml`
  [54578032] ADNLPModels v0.4.0
  [5c8ed15e] LinearOperators v2.3.2
  [a4795742] NLPModels v0.19.0
  [e01155f1] NLPModelsModifiers v0.6.1 `https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl#fix-bug-slack`
  [7998695d] NLPModelsTest v0.8.1
  [10f199a5] QPSReader v0.2.1
  [ae029012] Requires v1.3.0
  [ff4d7338] SolverCore v0.2.4
  [fa32481b] SparseMatricesCOO v0.1.1
  [37e2e46d] LinearAlgebra
  [2f01184e] SparseArrays
```

**Comment by geoffroyleconte** [comment]
Oh ok my bad I did not take the right branch. This does work for me too.

**Comment by tmigot** [comment]
Hey @geoffroyleconte ! It works well for me, now.

**Review by geoffroyleconte — APPROVED** [review]

**Pull request merged**
